name: any_logger_email
description: >-
  Email appender for any_logger with SMTP support, batching, HTML formatting,
  and rate limiting. Works with Gmail, Office 365, SendGrid, and more.

version: 1.1.2

homepage: https://github.com/raoulsson/any_logger_email
repository: https://github.com/raoulsson/any_logger_email

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  any_logger: ^1.1.2
  mailer: ^6.0.0

dev_dependencies:
  test: ^1.24.0

topics:
  - logging
  - email
  - smtp
  - alerts
  - monitoring

funding:
  - https://github.com/sponsors/raoulsson
  - https://www.buymeacoffee.com/raoulsson